/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class sample_Controller */

#ifndef _Included_sample_Controller
#define _Included_sample_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_Controller
 * Method:    uartFromc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_Controller_uartFromc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
